### ISSUE TITLE
Some doctor duties aren't carried out/no robots do fire duty

### ISSUE THREAD

**Issue by sdfg2** [alaestor/Rimworld-MiscRobotsPlusPlus#16] opened 2022-05-05 19:56 UTC
My ER and Omni bots aren't tending wounds or carrying out surgery.  And none of my bots are putting out fires.

**Comment by VeteranXT** [comment] 2022-11-29 17:27
They can't put fires. They dont have enabled Firefighter Worktype.

**Comment by alaestor** [comment] 2022-11-30 09:28
ER and Omnibots [should be able](https://github.com/alaestor/Rimworld-MiscRobotsPlusPlus/blob/dab736ffae2d9d2d02b904afce08ba534a98e56b/v1.4/Defs/ThingDefs/RPP_Races.xml#L715) to fight fires. Carrying (wounded and surgery) has been an issue in previous versions with it only working properly for some people, and I'm not sure if it's still a problem. It _may_ also be a mod conflict...

**Comment by VeteranXT** [comment] 2022-11-30 09:32
Depending on mod. For example Quality Builder will prevent bots to build any furniture with quality. Quality Surgeon also have similar issue. I was looking how to patch that and still figuring out. Quality Surgeon is mostly used on pawns.
Misc.Robots are "not" pawns. They are AIROBOT, a custom class that inherits Pawn Class. By default they should....but i need to check it more. 
Sadly i dont use Quality Surgeon/Builder due to bug.

**Comment by VeteranXT** [comment] 2022-12-10 16:10
I did test and found out since 1.4 no Doctor is present. Even if bot is assigned as doctor.
No matter what priority is set, game does not register bot as "Doctor" role, ER or Omni.

**Comment by VeteranXT** [comment] 2022-12-10 21:45
Well this just need harmony Patch...its problem comes form Rimwrold "WorkGiver_PatientGoToBedTreatment"
Misc.Robots are not controlled by player, no overseerSubject. 
We need to patch rimworld function.

**Comment by VeteranXT** [comment] 2022-12-11 22:27
This is fixed, waiting for merge.

**Comment by alaestor** [comment] 2022-12-12 09:19
confirmed fixed as of mv [3.4.11](https://github.com/alaestor/Rimworld-MiscRobotsPlusPlus/releases/tag/3.4.11)

**Closed by alaestor** 2022-12-12 09:19 UTC
