### ISSUE TITLE
Kitchen bot is having issues sowing

### ISSUE THREAD

**Issue by Muramas** [alaestor/Rimworld-MiscRobotsPlusPlus#15] opened 2022-03-02 06:49 UTC
I have removed all my mods and just kept DLCs + harmony + required mods + Robot++
I am running 1.3.3287

Currently when I try to sow in a growing zone the bot randomly picks a spot to grow in the zone instead of planting beside itself and planting to the closest spot. So if you grow in any large sized plot, the bot spends more time running around than sowing.

I have tested this with all the kinds of Kitchen bot and Omni bot and they all do the same thing.

I don't know if its a config on my side or a bug introduced with updates but it didn't do this in the past. Can anyone confirm that this is also happening to them?

**Comment by acorrow** [comment] 2022-03-04 14:30
Happens with an Omni bot as well. Here's the error:

`RimWorld.WorkGiver_GrowerSow provided target (143, 0, 79), Map_0 but yielded no actual job for pawn OmniBot 5. The CanGiveJob and JobOnX methods may not be synchronized.
UnityEngine.StackTraceUtility:ExtractStackTrace ()
Verse.Log:Error (string)
Verse.Log:ErrorOnce (string,int)
AIRobot.X2_JobGiver_Work:TryIssueJobPackage (Verse.Pawn,Verse.AI.JobIssueParams)
Verse.AI.ThinkNode_PrioritySorter:TryIssueJobPackage (Verse.Pawn,Verse.AI.JobIssueParams)
Verse.AI.ThinkNode_Priority:TryIssueJobPackage (Verse.Pawn,Verse.AI.JobIssueParams)
Verse.AI.Pawn_JobTracker:DetermineNextJob (Verse.ThinkTreeDef&)
Verse.AI.Pawn_JobTracker:TryFindAndStartJob ()
Verse.AI.Pawn_JobTracker:EndCurrentJob (Verse.AI.JobCondition,bool,bool)
Verse.AI.Pawn_JobTracker:JobTrackerTick ()
Verse.Pawn:Tick ()
AIRobot.X2_AIRobot:Tick ()
Verse.TickList:Tick ()
Verse.TickManager:DoSingleTick ()
Verse.TickManager:TickManagerUpdate ()
Verse.Game:UpdatePlay ()
Verse.Root_Play:Update ()`

**Comment by acorrow** [comment] 2022-03-06 05:59
Think I found the issue, Its not here, its in the original Misc Robot code, specifically this commit:

https://github.com/HaploX1/RimWorld-Miscellaneous_Source/commit/54f358458bc13986612304128ed5902d1a19be34#diff-69e14a214f4c0c35a6a7f9089222d2b4dabbe0e0e33f05ec8174418cd0721920

I believe the author has a misunderstanding of reference values in .NET

I'm going to raise this on his git repo and see if I can just fix it up.

Specifically, you can see the sequential calls to assign out new "enumerable" objects (enumerable, enumerable2, 3, etc). However, these are just making new references to the original value. In case anyone stumbles on this and cares, the problem is:

`
Object somthing = new Object();
something.someStringProperty = "foo";
Object something2 = something;
something2.someStringProperty = "bar";
`

In this case: `something.someStringProperty` = `'bar"

You don't create a copy here, you create a reference, so when you later go back to look at `something` expecting it to have it's original value, it does not. `something2` is just a reference to `something` and when you modified the property (or did anything, maybe even dispose it...) you actually modified `something`. Reading the code in this commit, I expect that is not what they intended. My guess is the scenario is avoided but for some specifics, hence the sporadic nature of this error.

**Comment by acorrow** [comment] 2022-03-06 09:48
https://github.com/HaploX1/RimWorld-Miscellaneous_Source/issues/5

You can close this issue. It's not a bug in ++ its in the core robot code.

**Closed** 2022-11-30 09:17 UTC
